version: '3'

services:
    mysql:
        image: mymysql
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=test1
          - MYSQL_DATABASE=test
          - MYSQL_USER=test
          - MYSQL_PASSWORD=test
          - MYSQL_ROOT_HOST=%